SERVER_IP = "0.0.0.0"
CLIENT_IP = "127.0.0.1"


DIRECTORY_SEPERATOR = "\\"
STARTING_DIRECTORY = "malimg_original_dataset_imgs"
NEW_DATASET_DIRECTORY = "malimg_fixed_dataset_imgs"
TESTED_FILE = NEW_DATASET_DIRECTORY + DIRECTORY_SEPERATOR + "Unknown" + DIRECTORY_SEPERATOR + "temp.png"


FIRST_MESSAGE_LENGTH = 8
BUFFER_SIZE = 2048
NUMBER_OF_USERS = 1000
PORT = 1002
